name: deploy to npm

on:
  push:
    tags:
      - "*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: checkout current
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      #   - name: publish version
      #     id: publish_version
      #     run: echo "RELEASE_VERSION=${{ github.ref_name }}" >> $GITHUB_OUTPUT

      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      #   - name: npm version bump
      #     run: npm version --no-git-tag-version ${{ steps.publish_version.outputs.RELEASE_VERSION }}

      #   - name: push to github
      #     run: |
      #       git add .
      #       git commit -m "chore: publish version ${{ steps.publish_version.outputs.RELEASE_VERSION }}"
      #       git push origin HEAD:${{ github.event.repository.default_branch }}

      - name: npm publish
        run: |
          npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
          npm install
          npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
